### PR TITLE
Remove The Button

### PR DESCRIPTION
**Pull request by Achu2234**
Its Useless To Add They already blacklisted this repo

### CODE REVIEW

**Comment by BLUE-DEVIL1134** [comment]
Okay, I get it...
Thanks a lot @Achu2234, for your contribution to [[UltroidCLiTemplate](https://github.com/BLUE-DEVIL1134/UltroidCliTemplate/)].

Can you please explain to me why they blacklisted this repo? All this repo does is install a executable and is not a userbot...

**Comment by Achu2234** [comment]
> Okay, I get it... Thanks a lot @Achu2234, for your contribution to [[UltroidCLiTemplate](https://github.com/BLUE-DEVIL1134/UltroidCliTemplate/)].
> 
> Can you please explain to me why they blacklisted this repo? All this repo does is install a executable and is not a userbot...

sir try yourself making this UltroidCLiTemplate in railway

**Comment by Achu2234** [comment]
image

**Comment by Achu2234** [comment]
@BLUE-DEVIL1134

**Comment by Achu2234** [comment]
image

@BLUE-DEVIL1134

**Comment by BLUE-DEVIL1134** [comment]
Okay, i get it, can you send the 
image
Email address given there, my railway account doesn't work!

**Comment by Achu2234** [comment]
Its not a email
https://docs.google.com/forms/d/e/1FAIpQLSckFHLil4Gr8AmSIPyBvGaQUfWp0mxqooTaE4_clyMFepnrrA/viewform
this is link given

**Comment by Achu2234** [comment]
Not Allowed

Mirrors/Userbots
Torrent Aggregators
Crypto Miners
Hosting/Distribution of DMCA protected content
VNCs/Virtual desktops
Sending Spam
Anything Illegal

**Comment by Achu2234** [comment]
Allowed

Websites
APIs + Backends
Cron Jobs / Scheduled Jobs
ML Jobs
Code Servers

**Comment by iAkashPattnaik** [comment]
Thanks for your contribution @Achu2234 !

**Comment by Achu2234** [comment]
> Thanks for your contribution @Achu2234 !

welcome

**Pull request merged**
